In [8]:
#import kaggle library , if not present then install kaggle
#!pip install kaggle

In [15]:
# searching dataset related to our topic in kaggle

In [7]:
!kaggle datasets list -s "retail orders"

ref                                                             title                                                size  lastUpdated          downloadCount  voteCount  usabilityRating
--------------------------------------------------------------  --------------------------------------------------  -----  -------------------  -------------  ---------  ---------------
gabrielsantello/wholesale-and-retail-orders-dataset             Wholesale & Retail Orders Dataset                     3MB  2023-09-19 09:31:40           2396         40  1.0
ankitbansal06/retail-orders                                     Retail Orders                                       200KB  2024-04-13 08:31:36           7535         19  0.47058824
zusmani/pakistans-largest-ecommerce-dataset                     Pakistan's Largest E-Commerce Dataset                14MB  2021-01-19 11:42:57          11053        332  0.9705882
heeraldedhia/groceries-dataset                                  Groceries dataset                                   257KB  2020-09-17 04:36:08          59967        615  1.0
umerkk12/online-retail-business                                 Online Retail Business                                7MB  2021-01-20 03:42:36           2273         43  0.64705884
sureshmecad/supplement-sales-prediction                         Supplement Sales Prediction                           2MB  2021-09-17 08:09:33           2132         37  0.9411765
toxifarian/tesco-retail-store-clubcard-orders                   Tesco Retail Store Clubcard Orders                  172KB  2022-05-18 20:29:26            489          8  0.3529412
saadharoon27/superstore-dataset                                 SuperStore Dataset                                    1MB  2023-10-08 14:51:16           1836         26  0.7647059
census/business-and-industry-reports                            Business and Industry Reports                         7MB  2017-10-17 23:21:56           6411        131  0.8235294
shelvigarg/sales-forecasting-womart-store                       Sales Forecasting WOMart Store                        2MB  2021-09-20 08:16:56           2186         26  0.8235294
mohamedharris/supermart-grocery-sales-retail-analytics-dataset  Supermart Grocery Sales - Retail Analytics Dataset  191KB  2022-06-12 16:14:44          15643        199  0.88235295
datatattle/dt-mart-market-mix-modeling                          DT MART: Market Mix Modeling                         22MB  2020-09-06 16:24:07           1737         40  0.88235295
endofnight17j03/global-superstore                               Global Superstore                                     8MB  2024-02-07 04:08:06            802         47  0.8235294
prajwal6362venom/diwali-sales                                   Diwali Sales                                        213KB  2023-04-20 08:06:13           1352         14  0.5882353
zusmani/gufhtugu-publications-dataset-challenge                 Gufhtugu Publications Dataset Challenge             954KB  2021-01-29 14:11:37           2538        410  1.0
amandam1/walmart-stock-20122016                                 Walmart Daily Stock Prices 1972-2022                223KB  2022-06-25 15:57:45           1393         33  1.0
thedevastator/online-retail-transaction-records                 Online Retail Transaction Records                     9MB  2023-12-21 02:44:20           1527         29  1.0
thedevastator/online-retail-sales-and-customer-data             Online Retail Sales and Customer Data                 9MB  2023-12-21 02:51:42           2642         33  1.0
skeller/us-supply-chain-information-for-covid19                 US Supply Chain Information for COVID19             101MB  2020-04-01 03:55:40           3312         48  0.88235295
uttamp/store-data                                               Customer Retention Retail                             3MB  2021-03-05 18:30:31           3742         22  0.4117647

In [ ]:
#download the dataset which we want using ref

In [9]:
!kaggle datasets download -d "ankitbansal06/retail-orders"

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading retail-orders.zip to C:\Users\shail

  0%|          | 0.00/200k [00:00<?, ?B/s]
100%|##########| 200k/200k [00:00<00:00, 210kB/s]
100%|##########| 200k/200k [00:00<00:00, 210kB/s]

In [10]:
#unzip and read the data from dowlaoded dataset

In [11]:
import zipfile

In [14]:
#This line opens the ZIP file retail-orders.zip for reading
zip_ref = zipfile.ZipFile('retail-orders.zip')

In [ ]:
#Extracts all the contents of retail-orders.zip into a directory named Retail_Orders. If the Retail_Orders directory does not exist, it will be created.
zip_ref.extractall("Retail_Orders")

In [15]:
#import pandas library
import pandas as pd

In [ ]:
#read data from the file
df=pd.read_csv('orders.csv')
df

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [21]:
#handling null values 
df = pd.read_csv('orders.csv',na_values=['Not Available','unknown'])
df

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [23]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [25]:
#rename columns names, make them lower case
df.columns=df.columns.str.lower()

In [27]:
# replace space with underscore
df.columns=df.columns.str.replace(' ','_')

In [ ]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [29]:
#derive new columns discount , sale price and profit
df['discount']=df['list_price']*df['discount_percent']*.01

In [30]:
df['sale_price']= df['list_price']-df['discount']

In [31]:
df['profit']=df['sale_price']-df['cost_price']

In [32]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [37]:
df.dtypes

order_id              int64
order_date           object
ship_mode            object
segment              object
country              object
city                 object
state                object
postal_code           int64
region               object
category             object
sub_category         object
product_id           object
cost_price            int64
list_price            int64
quantity              int64
discount_percent      int64
discount            float64
sale_price          float64
profit              float64
dtype: object

In [38]:
#convert order date from object data type to datetime
df['order_date']=pd.to_datetime(df['order_date'],format="%Y-%m-%d")

In [39]:
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale_price                 float64
profit                     float64
dtype: object

In [40]:
#drop cost price list price and discount percent columns, use inplace=True which will modify existing df
df.drop(columns=['list_price','cost_price','discount_percent'],inplace=True)

In [41]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

In [91]:
#load the data into sql server 
import sqlalchemy as sal
from sqlalchemy import create_engine

In [94]:
from sqlalchemy import create_engine

# Create an SQLAlchemy engine
#password='MySqlPassword'
# my_retail_orders is database name
engine = create_engine('mysql+mysqlconnector://Username:password@localhost:3306/my_retail_orders')
engine.connect()

In [95]:
# Write DataFrame to SQL table, here table is retail_orders
df.to_sql('retail_orders', con=engine, if_exists='append', index=False)

-1